GET http://localhost:8000/users/
?limit=10
&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI1LCJlbWFpbCI6Ik1hcmtNaXJhQGVtYWlsLmNvbSIsImlhdCI6MTczMjA1MzY5NiwiZXhwIjoxNzMyMDU3Mjk2LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.tJrpBrNLyTd_YWvSqQWFq_ytrUbjfHd-28uzPTpfGBI

GET http://localhost:8000/users/1/
?userType=aluno
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiRGFuaWxvQ2FudXRvQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoicHJvZmVzc29yIiwiaWF0IjoxNzMzMDk2NjAxLCJleHAiOjE3MzMxMDAyMDEsImF1ZCI6ImxvY2FsaG9zdDo4MDAwIiwiaXNzIjoibG9jYWxob3N0OjgwMDAifQ.9zm8Hu7E-8Df792iK6LYGPGiIBInnwcu8kNvpBRTOh0

GET http://localhost:8000/users/
?limit=10
&page=1
&userType=aluno
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiRGFuaWxvQ2FudXRvQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoicHJvZmVzc29yIiwiaWF0IjoxNzMzMDk2NjAxLCJleHAiOjE3MzMxMDAyMDEsImF1ZCI6ImxvY2FsaG9zdDo4MDAwIiwiaXNzIjoibG9jYWxob3N0OjgwMDAifQ.9zm8Hu7E-8Df792iK6LYGPGiIBInnwcu8kNvpBRTOh0
