PATCH http://localhost:8000/users/professores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6Ik1pcmFAZW1haWwuY29tIiwidXNlclR5cGUiOiJhbHVubyIsImlhdCI6MTczMzE1NTM2MywiZXhwIjoxNzMzMTU4OTYzLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.eELJ3l2azMe4HHgPJA5BSNRIEj1rO5TCcomNRuoO9eI

{
    "id": 12,
    "email":"johndoetest3@email.com"
}

PATCH http://localhost:8000/users/alunos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6Ik1pcmFAZW1haWwuY29tIiwidXNlclR5cGUiOiJhbHVubyIsImlhdCI6MTczMzE1NTM2MywiZXhwIjoxNzMzMTU4OTYzLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.eELJ3l2azMe4HHgPJA5BSNRIEj1rO5TCcomNRuoO9eI

{
    "id": 15,
    "registrationNumber":2021014100
}