GET http://localhost:8000/users/
?limit=10
&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6Ik1pcmFAZW1haWwuY29tIiwidXNlclR5cGUiOiJhbHVubyIsImlhdCI6MTczMzE1NTM2MywiZXhwIjoxNzMzMTU4OTYzLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.eELJ3l2azMe4HHgPJA5BSNRIEj1rO5TCcomNRuoO9eI

GET http://localhost:8000/users/13/
?userType=professor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6Ik1pcmFAZW1haWwuY29tIiwidXNlclR5cGUiOiJhbHVubyIsImlhdCI6MTczMzE1NTM2MywiZXhwIjoxNzMzMTU4OTYzLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.eELJ3l2azMe4HHgPJA5BSNRIEj1rO5TCcomNRuoO9eI

GET http://localhost:8000/users/
?limit=10
&page=1
&userType=aluno
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6Ik1pcmFAZW1haWwuY29tIiwidXNlclR5cGUiOiJhbHVubyIsImlhdCI6MTczMzE1NTM2MywiZXhwIjoxNzMzMTU4OTYzLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.eELJ3l2azMe4HHgPJA5BSNRIEj1rO5TCcomNRuoO9eI
