POST http://localhost:8000/users/professores
Content-Type: application/json
{
    "name" : "Mathias",
    "email":"Mathias@email.com",
    "password":"MathiasCoelho@1",
    "dateBirth": "2001-03-16T07:46:32+00:00",
    "cpf":"44455566678",
    "cellphone":"12987654321",
    "identifier":"123456789"
}

POST http://localhost:8000/users/alunos
Content-Type: application/json
{
    "name" : "Maria",
    "email":"Maria@email.com",
    "password":"MariaMira@1",
    "dateBirth": "2001-03-16T07:46:32+00:00",
    "cpf":"44455566678",
    "cellphone":"12987654321",
    "registration": "2021014100",
    "course":"Ciência da Computação"
}

