GET http://localhost:8000/auth/me
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiQWRsZXJAZW1haWwuY29tIiwidXNlclR5cGUiOiJwcm9mZXNzb3IiLCJpYXQiOjE3MzI0ODUzNDcsImV4cCI6MTczMjQ4ODk0NywiYXVkIjoibG9jYWxob3N0OjgwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCJ9.9B2NWYR9yPvEhCtX3sqUCvqhgHw_WkEoqnKz2rLe5Tk