POST http://localhost:8000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJpYXQiOjE3MzIyMTE0NTYsImV4cCI6MTczMjI5Nzg1NiwiYXVkIjoibG9jYWxob3N0OjgwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCJ9.E9OmdOQ6kcZqWdSax1cvzj5B773TH4nqfS_r6CpGqy8"
}