POST http://localhost:8000/auth/sign-in
Content-Type: application/json

{
    "email":"Cleide@email.com",
    "password":"Professor@1"
}

POST http://localhost:8000/auth/sign-in
Content-Type: application/json

{
    "email":"Mira@email.com",
    "password":"Alunos@1"
}
