POST http://localhost:8000/disciplines
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6IkNsZWlkZUBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InByb2Zlc3NvciIsImlhdCI6MTczMzE1NTk4NCwiZXhwIjoxNzMzMTU5NTg0LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.ZUZy4j7e6kVcORa0Z25hBB4hPibULM3XAemc7Pj2xi0
{
    "name" :"Arquitetura de Computadores I",
    "code":"COM101",
    "ipCamera":"192.168.1.103",
    "startTime": "19:00",
    "endTime": "20:40"
}

POST http://localhost:8000/disciplines/27/students
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6IkNsZWlkZUBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InByb2Zlc3NvciIsImlhdCI6MTczMzE1NTk4NCwiZXhwIjoxNzMzMTU5NTg0LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.ZUZy4j7e6kVcORa0Z25hBB4hPibULM3XAemc7Pj2xi0
{
    "studentsId": [17,18]
}

POST http://localhost:8000/disciplines/connect-camera
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiRGFuaWxvQ2FudXRvQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoicHJvZmVzc29yIiwiaWF0IjoxNzMzMDg4NjcyLCJleHAiOjE3MzMwOTIyNzIsImF1ZCI6ImxvY2FsaG9zdDo4MDAwIiwiaXNzIjoibG9jYWxob3N0OjgwMDAifQ.z6xUhvMeF6jvN_32uTbvXuX7-UsDBOSGUcAe1UCsBVc
{
    "idDiscipline": 1,
    "timeCameraOn": 10
}