POST http://localhost:8000/disciplines
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiQWRsZXJAZW1haWwuY29tIiwidXNlclR5cGUiOiJwcm9mZXNzb3IiLCJpYXQiOjE3MzIyOTE4MDUsImV4cCI6MTczMjI5NTQwNSwiYXVkIjoibG9jYWxob3N0OjgwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCJ9.H85jHXWN6hCr8cqB4A3JaiA3yYfXlc_LajWjBXzcWTU
{
    "name" :"Cálculo C",
    "code":"MAT00C",
    "ipCamera":"192.168.1.103"
}