GET http://localhost:8000/disciplines
?limit=10
&page=1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6IkNsZWlkZUBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InByb2Zlc3NvciIsImlhdCI6MTczMzE1NTk4NCwiZXhwIjoxNzMzMTU5NTg0LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.ZUZy4j7e6kVcORa0Z25hBB4hPibULM3XAemc7Pj2xi0
GET http://localhost:8000/disciplines/27
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6IkNsZWlkZUBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InByb2Zlc3NvciIsImlhdCI6MTczMzE1NTk4NCwiZXhwIjoxNzMzMTU5NTg0LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.ZUZy4j7e6kVcORa0Z25hBB4hPibULM3XAemc7Pj2xi0

GET http://localhost:8000/disciplines/linked-disciplines/13
?userType=professor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6IkNsZWlkZUBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InByb2Zlc3NvciIsImlhdCI6MTczMzE1NTk4NCwiZXhwIjoxNzMzMTU5NTg0LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.ZUZy4j7e6kVcORa0Z25hBB4hPibULM3XAemc7Pj2xi0