GET http://localhost:8000/disciplines
?limit=10
&page=1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiQWRsZXJAZW1haWwuY29tIiwidXNlclR5cGUiOiJwcm9mZXNzb3IiLCJpYXQiOjE3MzI0ODUzNDcsImV4cCI6MTczMjQ4ODk0NywiYXVkIjoibG9jYWxob3N0OjgwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCJ9.9B2NWYR9yPvEhCtX3sqUCvqhgHw_WkEoqnKz2rLe5Tk
GET http://localhost:8000/disciplines/16
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiQWRsZXJAZW1haWwuY29tIiwidXNlclR5cGUiOiJwcm9mZXNzb3IiLCJpYXQiOjE3MzI1MDQ5NzMsImV4cCI6MTczMjUwODU3MywiYXVkIjoibG9jYWxob3N0OjgwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCJ9.dkP1xUh-B9XardSxtWr-LwH7MCWbLzglsIy0dWZGuKk

GET http://localhost:8000/disciplines/linked-disciplines/1
?userType=aluno
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiRGFuaWxvQ2FudXRvQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoicHJvZmVzc29yIiwiaWF0IjoxNzMyODA1MTI0LCJleHAiOjE3MzI4MDg3MjQsImF1ZCI6ImxvY2FsaG9zdDo4MDAwIiwiaXNzIjoibG9jYWxob3N0OjgwMDAifQ.l3b1Q35DK4zK8NpdB4rUtGpdENFlagr17IWxh2jInsk